# Generated by Django 4.2.1 on 2023-05-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_link', models.URLField(blank=True, null=True)),
                ('project_title', models.CharField(blank=True, max_length=100, null=True)),
                ('project_image', models.URLField(max_length=300)),
                ('project_description', models.CharField(max_length=2000)),
            ],
        ),
    ]
