# Generated by Django 4.2.1 on 2023-05-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_portfolio_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
