# Generated by Django 4.2.1 on 2023-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='./images'),
        ),
    ]
