# Generated by Django 4.2.1 on 2023-05-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_alter_profile_avatar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
